# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20160411_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name_plural': 'conductores'},
        ),
        migrations.AddField(
            model_name='conductor',
            name='contra',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
