# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20160411_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='contra',
            new_name='clave',
        ),
    ]
