# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20160411_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='clave',
            field=models.CharField(max_length=50, verbose_name='nueva clase'),
        ),
    ]
