# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20160411_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conductor',
            name='clave',
            field=models.CharField(max_length=50, verbose_name='nueva clave'),
        ),
    ]
