# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20160416_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='clave',
            field=models.CharField(blank=True, max_length=50, verbose_name='nueva clave'),
        ),
    ]
