# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 05:37
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20160422_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='color',
            field=colorful.fields.RGBColorField(default='#FFFFFF'),
            preserve_default=False,
        ),
    ]
