# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_perfil_perfilruta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterModelOptions(
            name='perfilruta',
            options={'verbose_name': 'suscripción', 'verbose_name_plural': 'suscripciones'},
        ),
    ]
