# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_auto_20160426_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario correspondiente'),
        ),
    ]
