# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_auto_20160426_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
