# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_auto_20160508_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='conductor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routes.Conductor'),
        ),
    ]
