# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import routes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_auto_20160509_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='usuario',
            field=models.CharField(default='D00000001', max_length=9, validators=[routes.validators.validateConductorUsername]),
            preserve_default=False,
        ),
    ]
